[project]
name = "cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["common"]

[tool.uv.sources]
common = { workspace = true }

[dependency-groups]
dev = [
    "ruff >= 0.8.1",
    "pytest >= 8.3.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"